[general]
import = [
  "~/.config/alacritty/fonts.toml",
  "~/.config/alacritty/catppuccin-mocha.toml"
  #"~/.config/alacritty/colors.toml"
]

[terminal]

[terminal.shell]
program = "/bin/zsh"
args = ["-1"]

[window]
padding.x = 8 
padding.y = 2
#opacity = 0.4

[env]
TERM = "xterm-256color"
