[colors.primary]
background = "#121212"
foreground = "#F39E60"

[colors.normal]
black = "#0a0a0a"
red = "#E16A54"
green = "#8abe8d"
yellow = "#d7ae5f"
blue = "#6791c9"
magenta = "#7C444F"
cyan = "#6791c9"
white = "#F39E60"

[colors.bright]
black = "#444444"
red = "#9F5255"
green = "#9fcfa2"
yellow = "#F39E60"
blue = "#7aa2d4"
magenta = "#E16A54"
cyan = "#749689"
white = "#f7c39e"

[colors.cursor]
text = "#121212"
cursor = "#F39E60"

[colors.selection]
text = "#F39E60"
background = "#323232"

[colors.search.matches]
foreground = "#121212"
background = "#d7ae5f"

[colors.search.focused_match]
foreground = "#121212"
background = "#7cae7f"
