[font]
size = 14.0

[font.normal]
family = "Hack"
style = "Bold"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"
